### ISSUE TITLE
perf gap with flexpolyline

### ISSUE THREAD

**Issue by urschrei** [georust/polyline#35]
The https://docs.rs/flexpolyline/0.1.0/flexpolyline/ crate runs the `bench_encode` benchmark in around 19 µs <s>330 ns</s> on my machine, vs 77 µs for our decode function. That's in the 3x ballpark. They seem to use a [lot](https://github.com/heremaps/flexible-polyline/blob/master/rust/src/lib.rs#L397) of [lookups](https://github.com/heremaps/flexible-polyline/blob/master/rust/src/lib.rs#L492-L519), which I imagine accounts for the difference, but it would be good to investigate.

**Comment by mattiZed** [comment]
I have looked into their code, I assume you're right, the speed up comes from the explicit conversions via LUTs. In their algorithm they also need it because of the more complex char-map which is not just monotonically increasing from ASCII 63 as in GPolyline. I will try the approach while fixing #39.

**Comment by urschrei** [comment]
Addressed by #42, #43, #48, #49.
